<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernDotNet.LoanManagement.Application\ModernDotNet.LoanManagement.Application.csproj" />
    <ProjectReference Include="..\ModernDotNet.LoanManagement.Domain\ModernDotNet.LoanManagement.Domain.csproj" />
  </ItemGroup>

</Project>
